export const BUTTON_TEXT = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SEARCH: 'SEARCH',
    SHOW_COURSE: 'SHOW COURSE',
    ADD_NEW_COURSE: 'ADD NEW COURSE',
    CREATE_AUTHOR: 'CREATE AUTHOR',
    CREATE_COURSE: 'CREATE COURSE',
    CANCEL: 'CANCEL',
    BACK: 'BACK'
  } as const;
